# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.9"

  commands:
    # Install dependencies
    - pip install -e ".[docs]"
    # Build the MkDocs documentation
    - mkdocs build
    # Ensure the output directory exists
    - mkdir -p $READTHEDOCS_OUTPUT/html
    # Move the built site to the Read the Docs output directory
    - mv site/* $READTHEDOCS_OUTPUT/html

mkdocs:
  configuration: mkdocs.yml

search:
  ranking:
    # Push API docs in the /api directory down the ranking
    api/*: -5
