# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.9"

  jobs:
    post_create_environment:
      - pip install uv
    post_install:
      - |
          export SITE_URL="https://kedro.readthedocs.io/en/${READTHEDOCS_VERSION_NAME}/"
          echo "SITE_URL is $SITE_URL"
          python -c "import mkdocs.config; c=mkdocs.config.load_config(); print(f'Resolved site_url: {c[\"site_url\"]}')"
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv pip install .[docs]
      # Build the MkDocs documentation
      - mkdocs build
      # Ensure the output directory exists
      - mkdir -p $READTHEDOCS_OUTPUT/html
      # Move the built site to the Read the Docs output directory
      - mv site/* $READTHEDOCS_OUTPUT/html

mkdocs:
  configuration: mkdocs.yml

search:
  ranking:
    # Push API docs in the /api directory down the ranking
    api/*: -5
