# Override Vale.Repetition to exclude code blocks and inline code
extends: repetition
message: "'%s' is repeated!"
level: error
# Check all scopes except code
scope: '~code'
alpha: true
tokens:
  - '[^\s]+'
