@startuml
title "Installed Kedro project"

participant "third-party Python script" as script
participant "Directory with Kedro conf/ in it" as curr_dir
participant "KedroSession" as session

script->script: run third-party script
script->curr_dir: get path to the project config
script->session: create a session with Kedro project name and project config dir
session->run: run a pipeline and/or nodes

@enduml
