@startuml
title "$ kedro plugin"

participant "$ kedro plugin" as cli
participant "See kedro-with-project.puml for details" as prelude
participant "Kedro Plugin\nentry_point = kedro.project_commands" as project_plugin
participant "Click context" as click
participant "KedroSession" as session

cli->prelude: prepare click commands as prelude to this
prelude->project_plugin: execute plugin click command
project_plugin->click: get ProjectMetadata from the click context
project_plugin->project_plugin: plugin code
project_plugin->session: need to create KedroSession for all runtime config and info
@enduml
