name: Detect secrets on Kedro

on:
  workflow_call:
    inputs:
      os:
        type: string
      python-version:
        type: string
      branch:
        type: string
        default: ''

jobs:
  detect-secrets:
    permissions:
      contents: read
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
        with:
          ref: ${{ inputs.branch }}
      - name: Install the latest version of uv with Python ${{inputs.python-version}}
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          python-version: ${{ inputs.python-version }}
          activate-environment: true
      - name: Install dependencies
        run: |
          make install-test-requirements
          make install-pre-commit
      - name: pip freeze
        run: uv pip freeze --system
      - name: Scan all tracked files
        run: git ls-files -z | xargs -0 detect-secrets-hook --baseline .secrets.baseline
