@startuml
title "$ <project>\n$ python -m <project>.run"

participant "$ <project>\n$ python -m <project>" as cli
participant "setup.py\n<project> = <project>.~__main__" as entrypoint
participant "KedroSession" as session

cli->entrypoint: Python calls the entrypoint
entrypoint->session: create session
session->session: run

@enduml
